---
swagger: '2.0'
info:
  version: 0.1.0
  title: Talent IQ Candidate API
  contact:
    name: TalentIQ Support
    email: support@talentiq.co
  description: |
    # Introduction
    Welcome to TalentIQ’s API! You can use the API to programmatically interact with the TalentIQ data set for the purpose of data enrichment, updates,
    lead gen, form-fill, or anything else you can think of. The API is organized around REST . All requests return JSON, and HTTP are used to indicate errors.
    All requests should be made over SSL. All request and response bodies, including errors, are encoded in JSON.

    The endpoint of the API is:
    [https://api.talentiq.co/v2/person](https://api.talentiq.co/v2/person)

    If you or anyone on your team has any questions, feature requests, or suggestions, please feel free to reach out to us anytime at [support@talentiq.co](support@talentiq.co).

host: api.talentiq.co
basePath: "/v2"
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
